### ISSUE TITLE
How to use it without render function?

### ISSUE THREAD

**Issue by bachi76** [GIVESocialMovement/sbt-vuefy#12]
The provided example works fine when using a render function in index.scala.html. However, I'd rather want to not use a render function as simple "loader", but instead use custom tags like `<greeting-form>` in the Twirl template. E.g.

```html
@(greeting: String)

<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.16/vue.js"></script>
<script src='@routes.Assets.versioned("vue/components/greeting-form.js")'></script>

<div id="app">
    <p>Container</p>
    <greeting-form v-bind:greeting="'@greeting'">
</div>

<script>
    import('@routes.Assets.versioned("vue/components/greeting-form.js")').default
    Vue.component('greeting-form', GreetingForm);
    
    var app = new Vue({
        el: '#app'
    })
</script>
```

How can we achieve this behaviour?

Thanks!

**Comment by tanin47** [comment]
Yes, you can. And your code should work fine. There is one minor thing:

Could you remove `import('@routes.Assets.versioned("vue/components/greeting-form.js")').default`? I'm not sure whether importing the same JS twice entails.

Please note that GreetingForm is what is exported from `greeting-form.js`.

**Comment by bachi76** [comment]
ahh, thanks, that did the trick. Without `.default` (and the faulty import()), it would just throw
> vue.js:597 [Vue warn]: Failed to mount component: template or render function not defined.

Works like a charm now, thanks a lot! :)

**Comment by tanin47** [comment]
Glad it works :)
