### ISSUE TITLE
Add `"use strict";` to `sbt-vuefy-plugin.js`.

### ISSUE THREAD

**Issue by allenxiang** [GIVESocialMovement/sbt-vuefy#18]
Would you be able to add `"use strict";` to `sbt-vuefy-plugin.js`? Keep getting `SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` when I run sbt.

**Comment by tanin47** [comment]
Oh I didn't know that, and, yes, it makes sense to add `use strict;` in any case.

Do you happen to know why this happens on your machine but not mine?

**Comment by tanin47** [comment]
It seems you might on an older version of nodejs (https://stackoverflow.com/questions/33001246/uncaught-syntaxerror-block-scoped-declarations-let-const-function-class-no)

**Comment by tanin47** [comment]
Anyway, it makes sense to add `"use strict";`. Please use the newly published version: `1.3.0`. 

Thank you for suggesting the improvement!

**Comment by allenxiang** [comment]
Thanks a lot. This plugin works fine on my mac. But it does not work with on our Jenkins server. I have tried to install several different versions of NodeJS on Jenkins but none of them worked. Really weird situation.
