### ISSUE TITLE
How to use component with Play's Redirect statement

### ISSUE THREAD

**Issue by reinno** [GIVESocialMovement/sbt-vuefy#23]
Any suggestion about how vue works with Play's Redirect statement:

like in the controller will return 

```scala
Redirect(routes.Controller.viewSomething()).flashing("success" -> "success.")
```

then vue will get a response with the rendered html data.  Is it possible to use this data rerender the page in vue?

**Comment by tanin47** [comment]
Vue doesn't interface with a redirection. Like you mentioned, you can send data to Vue through HTML.

> Is it possible to use this data rerender the page in vue?

I'm not sure exactly what you meant here. Do you mean using the data from `flashing("success" -> "success.")`?

If so, then we need to figure out how `flashing` works. From https://www.playframework.com/documentation/2.6.x/ScalaSessionFlash#Flash-scope, it seems Flash uses cookies underneath.

After tracing the code, flashing data is kept in the cookie named `PLAY_FLASH` (https://github.com/playframework/playframework/blob/afa808bda4cb734e028c97443e0f10f3fd8ac404/framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala#L115)

You can write Javascript code to read that cookie and render in whatever way you want.

One detail that you might need to figure out is how to decode the content of cookies. Related: https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Flash.scala#L101

This might work asking on discuss.playframework.com about how to decode the flash cookie data.

**Comment by tanin47** [comment]
Ping @reinno, please let me know if this answers your question.

**Comment by tanin47** [comment]
I'm going to close this issue. If you have any more question, please feel free to re-open it.
