### ISSUE TITLE
'command line too long' error on Windows

### ISSUE THREAD

**Issue by liangzengle** [GIVESocialMovement/sbt-vuefy#27]
after creating a bunch files(simply copy `greeting-form.vue` up to 100), I was getting "command line too long" error when using `sbt stage` on my Windows10.

**Comment by tanin47** [comment]
Windows limits the length of command line to 8,191 characters (https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation). No idea why.

A good solution is to put all command arguments in a file. It seems, for Webpack, we can move all the arguments like `vue/components/greeting-form=/projects/sbt-vuefy/test-play-project/app/assets/vue/components/greeting-form.vue` into the generated webpack.config.js instead.

Thanks for using sbt-vuefy and thank you for reporting this interesting issue. I'll fix it within 24 hours.

**Comment by tanin47** [comment]
@liangzengle The fix has been release to `3.0.0` now. 

This is unrelated to your problem. You will need to change your `webpack.config.js` to not having those lines that contain `// required by sbt-vuefy`. In `3.0.0`, we inject those lines automatically for you. Please see `README.md` for more info and `test-play-project`'s `webpack.config.js` for a working example.

**Comment by liangzengle** [comment]
@tanin47 Problem solved, thanks.
