### ISSUE TITLE
sbt stage does not create a runnable production build

### ISSUE THREAD

**Issue by nathanielford** [GIVESocialMovement/sbt-vuefy#31]
The instruction indicate that to create production deployment, you should use `sbt stage`. However, in the basic test app this does not yield a runnable build:

```
$ sbt stage
[info] Loading settings for project plugins from plugin.sbt ...
[info] Loading settings for project sbt-vuefy-build from plugins.sbt ...
[info] Loading project definition from /Users/nford/echelon/sbt-vuefy/project
[info] Loading settings for project sbt-vuefy from version.sbt,build.sbt ...
[info] Loading project definition from /Users/nford/echelon/sbt-vuefy/test-play-project/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to test-play-project (in build file:/Users/nford/echelon/sbt-vuefy/test-play-project/)
[info] Packaging /Users/nford/echelon/sbt-vuefy/test-play-project/target/scala-2.12/test-play-project_2.12-1.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Wrote /Users/nford/echelon/sbt-vuefy/test-play-project/target/scala-2.12/test-play-project_2.12-1.0-SNAPSHOT.pom
[info] Main Scala API documentation to /Users/nford/echelon/sbt-vuefy/test-play-project/target/scala-2.12/api...
[info] [Vuefy] Compile on 1 changed files
[info] /Users/nford/echelon/sbt-vuefy/test-play-project/node_modules/webpack/bin/webpack.js --config /var/folders/83/9023vzns5vjd_fnfmtskwddw0000gp/T/sbt-vuefy3744603403231261495/webpack.config.js --output-path /Users/nford/echelon/sbt-vuefy/test-play-project/target/web/vuefy/main -p
Webpack for development
model contains 17 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/nford/echelon/sbt-vuefy/test-play-project/target/scala-2.12/test-play-project_2.12-1.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
   10 modules
[info] Webpack exited with 0
[info] [Vuefy] finished compilation in 11361 ms and generated 1 JS files
[info] Packaging /Users/nford/echelon/sbt-vuefy/test-play-project/target/scala-2.12/test-play-project_2.12-1.0-SNAPSHOT-web-assets.jar ...
[info] Done packaging.
[info] Packaging /Users/nford/echelon/sbt-vuefy/test-play-project/target/scala-2.12/test-play-project_2.12-1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /Users/nford/echelon/sbt-vuefy/test-play-project/target/scala-2.12/test-play-project_2.12-1.0-SNAPSHOT-sans-externalized.jar ...
[info] Done packaging.
$ ll target/universal/scripts/bin/
total 28
drwxr-xr-x 4 nford staff   128 Feb 14 14:51 .
drwxr-xr-x 3 nford staff    96 Feb 14 14:51 ..
-rwxr--r-- 1 nford staff 12575 Feb 14 14:51 test-play-project
-rw-r--r-- 1 nford staff  8441 Feb 14 14:51 test-play-project.bat
$ target/universal/scripts/bin/test-play-project -Dplay.http.secret.key='Q]WIB@IDFbM8odLosr[PyZJNT:r:tpP^I6iFV[ObJgcF@DQ3X`Hzu/aS?v?/aD:Q'
Error: Could not find or load main class play.core.server.ProdServerStart
Caused by: java.lang.ClassNotFoundException: play.core.server.ProdServerStart
```

(The key used here is just one I generated locally to test this plugin.)

Looking at the Play Framework [deployment documentation](https://www.playframework.com/documentation/2.7.x/Deploying) it seems like they recommend using `dist` for a production artifact and `stage` for testing production 'in place'. However, while using `dist` (as in `sbt dist`) creates a deployable artifact it doesn't seem to include any of the compiled javascript. Similarly, using `target/universal/stage/bin/test-play-project` results in a runnable application but no compiled Vue assets. (The server says the javascript doesn't exist.)

I'm by no means an sbt expert but I'm not clear what needs to be done to close the gap. In the documentation you indicate using the `-p` flag, but I don't know what that refers to (`sbt stage -p` just fails). Any thoughts on what might be going on here?

**Comment by tanin47** [comment]
Hi @nathanielford,

I never tried to stage the test-play-project before. So, there might be some problems.

When using `sbt stage`, we need to use `target/universal/stage/bin/test-play-project` (notice `stage` instead of `script`)

> Looking at the Play Framework [deployment documentation](https://www.playframework.com/documentation/2.7.x/Deploying) it seems like they recommend using `dist` for a production artifact and `stage` for testing production 'in place'.

At GIVE.asia, we deploy our system on Heroku, and it seems `sbt stage` is recommended. But we would love to make sbt-vuefy work with `sbt dist`.

But let's get it working for you on `sbt stage` first.

> Similarly, using `target/universal/stage/bin/test-play-project` results in a runnable application but no compiled Vue assets. (The server says the javascript doesn't exist.)

This is very strange. It works on my machine.

From your logs, the vue files are compiled.

Could you check if `/Users/nford/echelon/sbt-vuefy/test-play-project/target/web/vuefy/main` contains compiled Javascript files?

> I'm by no means an sbt expert but I'm not clear what needs to be done to close the gap. In the documentation you indicate using the `-p` flag, but I don't know what that refers to (`sbt stage -p` just fails)

Oh, the `-p` explanation means that, when you use `sbt stage`, we will add `-p` to the webpack command for you.

This is seen in `/Users/nford/echelon/sbt-vuefy/test-play-project/node_modules/webpack/bin/webpack.js --config /var/folders/83/9023vzns5vjd_fnfmtskwddw0000gp/T/sbt-vuefy3744603403231261495/webpack.config.js --output-path /Users/nford/echelon/sbt-vuefy/test-play-project/target/web/vuefy/main -p`

Thank you for trying sbt-vuefy. Please let me know what is inside `/Users/nford/echelon/sbt-vuefy/test-play-project/target/web/vuefy/main` after running `sbt stage`.

**Comment by nathanielford** [comment]
Thanks so much for helping out! I really appreciate it, as I'm really excited to use Vue with a Scala stack on the backend. I also appreciate the explanation of the -p flag.

So I did a complete wipe and restarted from scratch and it works now... I apologize for the noise. Not sure what went sideways, unfortunately, but I reinstalled yarn and npm, too, so I wonder if I was in some silent bad state for no good reason. Thank you again SO MUCH for taking the time to help. Really excited about this plugin!
 
My next step is to attempt to work with `dist`, but I'm aiming to try and create a deployable Docker artifact. Will let you know how it goes!

**Comment by tanin47** [comment]
@nathanielford sbt-vuefy integrates into Playframework's asset pipeline, so `sbt dist` should work fine.

I just tested it, and it worked on my machine:

```
$ sbt dist 
$ cd target/universal/
$ unzip test-play-project-1.0-SNAPSHOT.zip
$ ./test-play-project-1.0-SNAPSHOT/bin/test-play-project -Dplay.http.secret.key=sdfsdf
[info] play.api.Play - Application started (Prod)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
```

Please feel free to re-open an issue if you can't get it to work.

Thank you again for trying sbt-vuefy. I hope we can help you get this to production!
