### ISSUE TITLE
vue-resource in multiple components : should I have a main.js file ?

### ISSUE THREAD

**Issue by juliender** [GIVESocialMovement/sbt-vuefy#33]
Hi, 

I try to import and use `vue-resource` in multiple components.
First, I tried to import in each single file component, but got the error `Cannot redefine property: $url`

Second, I tried to import vue-resource in the index.scala.html, when instancianting Vue : 

```
<script>
    import Vue from 'Vue'
    import Resource from 'vue-resource';
    Vue.use(Resource);

    Vue.config.productionTip = false

    Vue.component('v-header', Header.default);
    Vue.component('product-page-cart', Product.default);

    new Vue({
      el: '#app',
      data: ... 
</script>
```

But I get the TypeScript compilation error on my component files :  `Property '$http' does not exist`

I now try to have a main.js file, but still gets the `$http does not exists` error.

How do you get `vue-resource` working in a realworld project ?

Regards

**Comment by tanin47** [comment]
Hey @juliender, 

First of all thank you for using sbt-vuefy. 

Now I'm not sure where `Cannot redefine property: $url` and `Property '$http' does not exist` come from. So, I have a few questions:

* Is this the vue-resource (https://github.com/pagekit/vue-resource) you are using? 
* Could you provide the full stacktrace and, if possible, the code for this whole file and webpack.config.js?

We never use vue-resource. So, we aren't familiar with it. But I'm sure we can resolve this issue.

**Comment by juliender** [comment]
Thank you for this plugin ! :)

This is the plugin I use, and this is the recommended library for http requests.
What do you use for backend requests, from the Vue components ?

The `$url` error appears when adding the library twice (in each component) through the `Vue.use` function. On the "Vue.use" line.
The `$http` error appears when the library is not imported (neither in the component, nor in the main.scala.html, seems you can't import libs from main.scala.html)

So, I don't manage to import the library properly. I think the main purpose is 
- either to get a working `main.js`, in order to have a clean import management with npm and vue build mecanisms. (I think about moving from sbt-vuefy to the complete Vue build system)
- or dirty solution, I don't know if it's possible : have the *.vue components compiled to *.js files (the purpose of sbt-vuefy) but without all the typescript verifications about types and imports etc (Maybe this wont work better)

I will send you the code + stacktrace tomorrow from the office.


**PS** : I found that there is the _axios_ library, i will have a look on it tomorrow. Maybe it's much more easy this way.
An other idea, maybe I should have only 1 main component defined in main.scala.js : a kind of `App.vue`
And all other components would be imported through the main one. That would fix issues when importing libraries twice. 
It's late, I try that tomorrow !

Regards

**Comment by tanin47** [comment]
> The $url error appears when adding the library twice (in each component) through the Vue.use function. On the "Vue.use" line.

Webpack should have deduped that in the bundle. This is super weird.

> The $http error appears when the library is not imported (neither in the component, nor in the main.scala.html, seems you can't import libs from main.scala.html)

There's a way to do it. For example, if `vue` is imported directly through main.scala.html, then your webpack config must contain:

```  
 externals: {
    // The below allows `import Vue from 'vue'` without including Vue in the bundle.
    vue: 'Vue'
  },
```
> I found that there is the axios library, i will have a look on it tomorrow. Maybe it's much more easy this way.

At GIVE.asia, we use axios. But it should have worked with vue-resource as well.

**Comment by juliender** [comment]
Before I go with axios, this is my code, taken from the test-play-project folder

- The webpack.config.js
- The main.scala.html
- One component (header) but the others are the same


**webpack.config.js  at project's root :** 

```
"use strict";

const VueLoaderPlugin = require('vue-loader/lib/plugin');

module.exports = {
    plugins: [new VueLoaderPlugin()],
    stats: 'minimal',
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
            },
            {
                test: /\.scss$/,
                exclude: /node_modules/,
                use: [
                    'vue-style-loader',
                    'css-loader',
                    'sass-loader'
                ],
            },
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                options: {
                    appendTsSuffixTo: [/\.vue$/],
                }
            }
        ]
    },
    resolve: {
        extensions: ['.ts', '.js', '.vue']
    },
};
```
**main.scala.html**
```
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

        <script src="@routes.Assets.versioned("vue/Header.js")"></script>
        @*<script src="@routes.Assets.versioned("vue/Product.js")"></script>*@
        <script>
          Vue.component('v-header', Header.default);
          // Vue.component('product-page-cart', Product.default);

          new Vue({
            el: '#app',
            data:
                function() {
                    return {
                        pro: false,
                        cartVisible: false
                    }
                },
            methods: {
                // HP, shop, tuto ...
                addToCart: function (id) {
                    this.$http.post('/api/cart', {
                        id: id,
                        qty: 0
                    }).then(response => {
                        this.$root.$emit('updateCart', response.data.cart);
                    });

                },
                // on product page, outside the cart component
                updateCart: function (id) {
                    this.$root.$emit('getCart');
                }
            }
        });
        </script>
```

**Header.vue component in app/vue/ **

```
<script lang="ts">
    import Vue from 'vue';

    import Resource from 'vue-resource';
    Vue.use(Resource);

    export default Vue.extend({
        data: function () {
            return {
                cart: {count: 0, price: 0},
            }
        },
        mounted() {
            if (localStorage.cart) {
                this.cart = localStorage.cart;
            }
            this.getCart();

            this.$root.$on('updateCart', data => {
                this.cart = data
            });
            this.$root.$on('getCart', data => {
                this.getCart()
            });
        },
        methods: {
            getCart: function () {
                this.$http.get('/api/cart/summary').then(response => {
                    this.cart = response.data.cart;
                    // $('#cart_container').html(response.data.cartHtml);
                }, response => {
                    if (response.status === 404) {
                        this.cart.count = 0;
                        this.cart.price = 0;
                    }
                });
            },
        }
    });
</script>
```

**Comment by juliender** [comment]
> > The $url error appears when adding the library twice (in each component) through the Vue.use function. On the "Vue.use" line.
> 
> Webpack should have deduped that in the bundle. This is super weird.

I am a beginner with vue/webpack (built my previous projects with angular)
But the line `Vue.use .. `  is code, not library management, and I dont think webpack processes code ?
> 
> > The $http error appears when the library is not imported (neither in the component, nor in the main.scala.html, seems you can't import libs from main.scala.html)
> 
> There's a way to do it. For example, if `vue` is imported directly through main.scala.html, then your webpack config must contain:
> 
> ```
>  externals: {
>     // The below allows `import Vue from 'vue'` without including Vue in the bundle.
>     vue: 'Vue'
>   },
> ```
Same here, still missing the "Vue.use" line, required for vue-resource setup
> 
> > I found that there is the axios library, i will have a look on it tomorrow. Maybe it's much more easy this way.
> 
> At GIVE.asia, we use axios. But it should have worked with vue-resource as well.

So you dont have to call `Vue.use` ?

**Comment by juliender** [comment]
This is my updated code with an main component named App.vue.
I can use vue-resource, but I moved anyway to axios.
Both cases, i dont have any error :)

Thanks for help !

**main.scala.html**
```

        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>

        <script  src="@routes.Assets.versioned("vue/App.js")"></script>
        <script>
            new Vue({
                el: '#app',
                components: {
                    'v-app': App.default,
                }
            });
        </script>

```


**App.vue**
```
<script lang="ts">
    import Vue from 'vue';
    import Header from './Header.vue';
    import Product from './Product.vue';

    import VueResource from 'vue-resource';
    Vue.use(VueResource);

    export default Vue.extend({
        components: {
            'v-header': Header,
            'v-product': Product,
        },
        data:
            function() {
                return {
                    ...
                }
            },
        methods: {
            ...
        }
    });
</script>
```


**and a component for example Header.vue**
```
<script lang="ts">
    import Vue from 'vue';

    export default Vue.extend({
        data: function () {
            return {
                cart: {count: 0, price: 0},
            }
        },
        methods: {
            getCart: function () {
                this.$http.get('/api/cart/summary').then(response => {
                    this.cart = response.data.cart;
                }, response => {
                    if (response.status === 404) {
                        this.cart.count = 0;
                        this.cart.price = 0;
                    }
                });
            },
        }
    });
</script>
```

**Comment by tanin47** [comment]
> But the line Vue.use .. is code, not library management, and I dont think webpack processes code ?

You're right. `Vue.use` is a JS code and has nothing to do with Webpack. And I've never use `Vue.use` before.

It seems like `Vue.use` should be idempotent (i.e. invoking multiple times should not be an issue) -- https://vuejs.org/v2/api/#Vue-use
