### ISSUE TITLE
Bintray Repository deprecated

### ISSUE THREAD

**Issue by yosabre** [GIVESocialMovement/sbt-vuefy#40]
Since 1st of May, the bintray repository has been deprecated. Could we move the packages to some other repository?

**Comment by tanin47** [comment]
I will find a new repo tomorrow. I apologize for the inconvenience.

**Comment by tanin47** [comment]
@yosabre you can use this instead: `addSbtPlugin("io.github.givesocialmovement" % "sbt-vuefy" % "6.0.0")`

The readme has been updated. Thank you.
