### ISSUE TITLE
Bintray repo not available anymore

### ISSUE THREAD

**Issue by max-preuschen** [GIVESocialMovement/sbt-vuefy#41]
Thank you for the sbt-vuefy plugin!
Our project-build recently started failing, because the Bintray repo isn't available anymore.
Is there a plan to move to another repo soon?

We're using version `5.0.0`

Many thanks

**Comment by tanin47** [comment]
I'll take a look tomorrow. I apologize for the inconvenience.

**Comment by tanin47** [comment]
@max-preuschen you can use this: `addSbtPlugin("io.github.givesocialmovement" % "sbt-vuefy" % "5.0.0")`. Thank you.
