### ISSUE TITLE
Error in Build.sbt

### ISSUE THREAD

**Issue by JohnathanZhou** [GIVESocialMovement/sbt-vuefy#7]
My project isn't compiling due to an error in the build.sbt -- it's giving an error `value / is not a member of sbt.Configuration`

It also points to the / in the line `Assets / Vuekeys.vuefy ...` and says that there's an type error in expression -- how should i resolve this?

**Comment by tanin47** [comment]
Hi @JohnathanZhou,

What sbt version are you using?  `/` might be a new syntax for later versions of sbt.

In any case, here's a working `build.sbt` (https://github.com/GIVESocialMovement/sbt-vuefy/blob/master/test-play-project/build.sbt).

**Comment by JohnathanZhou** [comment]
It says I'm on version 1.0.3. What's the right way to update my version?

**Comment by tanin47** [comment]
You can change the value in `project/build.properties`, for example, https://github.com/GIVESocialMovement/sbt-vuefy/blob/master/test-play-project/project/build.properties

Here are other important points:
* https://github.com/GIVESocialMovement/sbt-vuefy/blob/master/test-play-project/project/plugin.sbt --- you need to add sbt-vuefy as a plugin
* https://github.com/GIVESocialMovement/sbt-vuefy/blob/master/test-play-project/build.sbt --- you also need to `enablePlugins(SbtVuefy)`. (I forgot to mention this in `README.md`)

**Comment by JohnathanZhou** [comment]
I did all those things and it compiles now. However, I'm now getting the error 
`IOException: Cannot run program ".../node_modules/.bin/webpack" (in directory ".../app/assets"): error = 2, No such file or directory`

**Comment by JohnathanZhou** [comment]
I did install the binary and set up the webpack.config but I'm still getting the issues. I've also followed your example project a bit too but I'm still getting the same error as earlier (File not found)

**Comment by tanin47** [comment]
The path to webpack binary is definitely wrong here. 

`Assets / VueKeys.vuefy / VueKeys.webpackBinary` should point to the webpack binary. If the relative path doesn't work, try an absolute path to debug.

Could you share your build.sbt?

**Comment by tanin47** [comment]
Have you successfully used it? If not, it might be good to try our example directly (https://github.com/GIVESocialMovement/sbt-vuefy/blob/master/test-play-project)

**Comment by JohnathanZhou** [comment]
I can't start off of the example because I'm use vue in a current play application. However, I've gotten the webpack to work properly now and the files are compiling into the `web/vuefy/...` folder. The issue now is `play.api.libs.json.JsResultException: JsResultException(errors:List(((0),List(JsonValidationError(List(error.expected.jsstring),WrappedArray())))))`. I've looked into it but I have no idea how to fix it

**Comment by tanin47** [comment]
Good to hear.

I'm gonna close this issue then.
